language: rust
sudo: false
os: linux
dist: trusty

rust:
  - nightly
  - beta
  - stable
  - 1.17.0

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

notifications:
  webhooks: http://build.servo.org:54856/travis
  email:
    on_success: never

env:
  - RUST_BACKTRACE=1

script:
  - cargo build --verbose
  - cargo doc   --verbose --no-deps

  - cargo test  --verbose
  - cargo test  --verbose --features 'with_serde'

  # Stop here if not running on nightly rust
  - if [ "$TRAVIS_RUST_VERSION" != "nightly" ] ; then exit ; fi

  - cargo test  --verbose --features 'bench_it'
  - cargo bench --verbose --features 'bench_it'

  - cargo test  --verbose --features 'flame_it'
  - cargo run   --verbose --features 'flame_it' --example 'flame_udhr'
