language: rust
sudo: false
os: linux
dist: trusty

rust:
  - nightly
  - beta
  - stable
  - 1.15.0

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

notifications:
  webhooks: http://build.servo.org:54856/travis
  email:
    on_success: never

script:
  - cargo build --verbose
  - cargo doc   --verbose --no-deps

  - RUST_BACKTRACE=1 cargo test  --verbose
  - RUST_BACKTRACE=1 cargo test  --verbose --features with_serde

  - if [ "$TRAVIS_RUST_VERSION" != "nightly" ] ; then exit ; fi

  - RUST_BACKTRACE=1 cargo test --verbose --features bench_it
  - RUST_BACKTRACE=1 cargo test --verbose --features flame_it

  - cargo run --verbose --features flame_it --example flame_udhr

  - cargo bench --verbose --features bench_it
