language: rust
sudo: false

rust:
  - nightly
  - beta
  - stable
  - 1.15.0

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

notifications:
  webhooks: http://build.servo.org:54856/travis
  email:
    on_success: never

before_script:
  - pip install git+https://github.com/euclio/travis-cargo@kcov --user && export PATH=$HOME/.local/bin:$PATH

script:
  - cargo build --verbose
  - cargo test  --verbose
  - cargo test  --verbose --features with_serde
  - cargo doc   --verbose --no-deps
  - travis-cargo bench
